/**
 * @file constants
 */
export const TOGGLE_FORM = "GUEST_UNITS_PAGE/TOGGLE_FORM";
export const TOGGLE_MODAL = "GUEST_UNITS_PAGE/TOGGLE_MODAL";

/*---------------------------------------------------------------------*/
export const GET_ALL_TERMS_OF_UNIT = "GUEST_UNITS_PAGE/GET_ALL_TERMS_OF_UNIT";
export const GET_ALL_TERMS_OF_UNIT_SUCCESS = "GUEST_UNITS_PAGE/GET_ALL_TERMS_OF_UNIT_SUCCESS";
export const GET_ALL_TERMS_OF_UNIT_FAIL = "GUEST_UNITS_PAGE/GET_ALL_TERMS_OF_UNIT_FAIL";

export const GET_INTRODUCE = "GUEST_UNITS_PAGE/GET_INTRODUCE";
export const GET_INTRODUCE_SUCCESS = "GUEST_UNITS_PAGE/GET_INTRODUCE_SUCCESS";
export const GET_INTRODUCE_FAIL = "GUEST_UNITS_PAGE/GET_INTRODUCE_FAIL";

export const GET_STRUCTURE_BY_TERM = "GUEST_UNITS_PAGE/GET_STRUCTURE_BY_TERM";
export const GET_STRUCTURE_BY_TERM_SUCCESS = "GUEST_UNITS_PAGE/GET_STRUCTURE_BY_TERM_SUCCESS";
export const GET_STRUCTURE_BY_TERM_FAIL = "GUEST_UNITS_PAGE/GET_STRUCTURE_BY_TERM_FAIL";
/*---------------------------------------------------------------------*/
export const HANDLE_CLEAR = "GUEST_UNITS_PAGE/HANDLE_CLEAR";
export const HANDLE_MEMBER_DETAIL = "GUEST_UNITS_PAGE/HANDLE_MEMBER_DETAIL";
export const HANDLE_TAB_CHANGE = "GUEST_UNITS_PAGE/HANDLE_TAB_CHANGE";
export const HANDLE_INPUT_CHANGE = "GUEST_UNITS_PAGE/HANDLE_INPUT_CHANGE";